# -*- coding: utf-8 -*-
"""intern_H/W

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lO4oGrNOL4uRez5HjhSXpWg2Zxq9t-2K
"""

import numpy as np
import pandas as pd

su_ga=np.load('/content/sudoku_game.npy')
su_ga

flatten_game = su_ga.flatten()

flatten_game #1D te pey jabo

#Reshape korbo 1D theke onno ekta structure debo
rs_game = flatten_game.reshape((9,8))  # var_name.reshape((ROW,COLUNM))
rs_game

np.array([1.22,900,56.79]).dtype

su_ga

su_ga[:5] #Suru theke 5no. row obdi

su_ga[2:4] #row 2 er por and row 4 er agge obdi

su_ga[:,5] #Column no.5 only print korbe

su_ga[:,5:8]

arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr

arr[:5]

arr[5:]

arr[2:4]

su_ga

#slicing 2D array
su_ga[2:4,2:4] #su_ga[ROW_start : ROW_end , Column_start : Column_end]

np.sort(su_ga) #each row te boro theke choto kore sajabe

#Keep in Mind in a Matrix Rows Considered as Axis=1 Cols Considers as Axis=0
np.sort(su_ga,axis=1) #row wise sort

np.sort(su_ga,axis=0) #column wise sort

